apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-ak-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: admin-app
  template:
    metadata:
      labels:
        app: admin-app
    spec:
      containers:
      - name: my-admin-app
        image: 240088057918.dkr.ecr.us-east-1.amazonaws.com/docker-image-administrator:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8085
# service type loadbalancer
---
apiVersion: v1
kind: Service
metadata:
  name: admin-app-svc
spec:
  selector:
    app: admin-app
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085
  type: LoadBalancer
